### ISSUE TITLE
Can't re-add Spaudion to Spotify 3rd party app access

### ISSUE THREAD

**Issue by VisualisationExpo** [irskep/spaudion#2]
Hi Steve,

Have you had any other comments/e-mails on Spaudion not wanting to connect to Spotify or vice-versa? I tried reaching out on one of your social media platforms that isn't Mastodon, but I sensed you we're long gone from Twitter.

I haven't been able to add Spaudion back. I foolishy removed Spaudion while wanting to remove some other apps access

The issue with re-adding Spaudion to access my Spotify Premium account hinders my work on a skin for Audion/Spaudion.

Perhaps I could try and stop, and then restart Premium access on Spotify

**Comment by irskep** [comment]
Honestly I have no idea. I don't actively maintain this app and I'm shocked anyone uses it for real. 🙂

**Comment by VisualisationExpo** [comment]
It's okay.. Spaudion and of course the OG app; Audion, are just about the only thing still working on Monterey with regards to have a player have skins in the way Bowtie did.

**Comment by VisualisationExpo** [comment]
Solution was to quit out of Velja - the app by Sindre Sorhus.. while that was running Spaudion and Spotify couldn't connect.

Back in business.

Only thing I need ask is that Audion is not 4.0.2 - do we know what Spaudion is missing from that particular version seeing Spaudion is using the 4.0.0 build of Audion - could the fork benefit from the advances from Audion?

I am well aware that Audion isn't actively developed. I used it in the past when it was actively developed and have a license for it somewhere. Just curious.
Favorite face from back then was Sascha Höhne's Y5.2 and TouchScreenII by David Parise.
